# Generated by Django 4.1.7 on 2023-03-17 15:04

from django.db import migrations, models
import image_optimizer.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the scholarship', max_length=255)),
                ('country', models.CharField(choices=[('AF', 'Afghanistan'), ('AX', 'Aland Islands'), ('AL', 'Albania'), ('DZ', 'Algeria'), ('AS', 'American Samoa'), ('AD', 'Andorra'), ('IN', 'India'), ('ID', 'Indonesia'), ('IR', 'Iran'), ('IQ', 'Iraq'), ('IE', 'Ireland'), ('GB', 'United Kingdom'), ('US', 'United States'), ('UY', 'Uruguay'), ('UZ', 'Uzbekistan'), ('VU', 'Vanuatu'), ('VA', 'Vatican City'), ('VE', 'Venezuela'), ('VN', 'Vietnam'), ('WF', 'Wallis and Futuna'), ('EH', 'Western Sahara')], help_text='Country of the scholarship', max_length=255)),
                ('description', models.TextField(help_text='Description of the scholarship')),
                ('eligibility', models.TextField(help_text='Eligibility criteria for the scholarship')),
                ('last_date', models.DateField(help_text='Last date to apply for the scholarship')),
                ('link', models.URLField(help_text='Link to the scholarship page')),
                ('image', image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='scholarship_pics')),
            ],
        ),
    ]
