# Generated by Django 4.1.7 on 2023-03-18 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0002_alter_scholarship_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='amount',
            field=models.CharField(default='$100', help_text='Amount of the scholarship', max_length=255),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='last_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 17, 1, 38, 38, 298759, tzinfo=datetime.timezone.utc), help_text='Last date to apply for the scholarship'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='winner_announcement_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 2, 1, 38, 38, 298759, tzinfo=datetime.timezone.utc), help_text='Date when the winner will be announced'),
        ),
    ]
