# Generated by Django 4.1.7 on 2023-04-13 04:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0003_scholarship_amount_alter_scholarship_last_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='last_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 13, 4, 19, 10, 97363, tzinfo=datetime.timezone.utc), help_text='Last date to apply for the scholarship'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='winner_announcement_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 28, 4, 19, 10, 97363, tzinfo=datetime.timezone.utc), help_text='Date when the winner will be announced'),
        ),
    ]
