# Generated by Django 4.1.7 on 2023-04-13 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0006_scholarship_education_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='education_level',
            field=models.IntegerField(default=1, help_text='Education level of the scholarship'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='last_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 13, 4, 40, 56, 849272, tzinfo=datetime.timezone.utc), help_text='Last date to apply for the scholarship'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='winner_announcement_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 28, 4, 40, 56, 849272, tzinfo=datetime.timezone.utc), help_text='Date when the winner will be announced'),
        ),
    ]
