# Generated by Django 4.1.7 on 2023-04-13 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0007_alter_scholarship_education_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='education_level',
            field=models.IntegerField(choices=[('1', 'B.Tech'), ('2', 'M.Tech'), ('3', 'B.Sc'), ('4', 'M.Sc'), ('5', 'B.Com'), ('6', 'M.Com'), ('7', 'B.A'), ('8', 'M.A'), ('9', 'B.B.A'), ('10', 'M.B.A'), ('11', 'B.C.A'), ('12', 'M.C.A'), ('13', 'B.Pharm'), ('14', 'M.Pharm'), ('15', 'B.D.S'), ('16', 'M.D'), ('17', 'M.B.B.S'), ('24', 'B.Des'), ('25', 'M.Des'), ('26', 'B.F.A'), ('27', 'M.F.A'), ('28', 'B.Voc'), ('29', 'M.Voc'), ('30', 'B.Arch'), ('31', 'M.Arch'), ('32', 'B.Lib'), ('33', 'M.Lib'), ('34', 'Other')], default='1'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='last_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 13, 4, 41, 55, 674423, tzinfo=datetime.timezone.utc), help_text='Last date to apply for the scholarship'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='winner_announcement_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 28, 4, 41, 55, 674423, tzinfo=datetime.timezone.utc), help_text='Date when the winner will be announced'),
        ),
    ]
