# Generated by Django 4.1.7 on 2023-04-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(choices=[('1', 'B.Tech'), ('2', 'M.Tech'), ('3', 'B.Sc'), ('4', 'M.Sc'), ('5', 'B.Com'), ('6', 'M.Com'), ('7', 'B.A'), ('8', 'M.A'), ('9', 'B.B.A'), ('10', 'M.B.A'), ('11', 'B.C.A'), ('12', 'M.C.A'), ('13', 'B.Pharm'), ('14', 'M.Pharm'), ('15', 'B.D.S'), ('16', 'M.D'), ('17', 'M.B.B.S'), ('24', 'B.Des'), ('25', 'M.Des'), ('26', 'B.F.A'), ('27', 'M.F.A'), ('28', 'B.Voc'), ('29', 'M.Voc'), ('30', 'B.Arch'), ('31', 'M.Arch'), ('32', 'B.Lib'), ('33', 'M.Lib'), ('34', 'Other')], default='1', max_length=2),
        ),
    ]
